# Generated by Django 4.2 on 2023-04-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_column='name', max_length=65)),
                ('email', models.CharField(max_length=65)),
                ('mensagem', models.CharField(db_column='message', max_length=5000)),
            ],
        ),
    ]
